config/routes.rb
Rails.application.routes.draw do

  resources :products

  root to: 'home#index'
  get 'aboutus', to: 'home#aboutus', as: 'aboutus'
  get 'boardgames', to: 'products#boardgames', as: 'boardgames'
  get 'tradingcards', to: 'products#tradingcards', as: 'tradingcards'
  get 'miniatures', to: 'products#miniatures', as: 'miniatures'
  get 'roleplaying', to: 'products#roleplaying', as: 'roleplaying'
  get 'accessories', to: 'products#accessories', as: 'accessories'
  get 'search_results', to: 'products#search_results', as: 'search_results'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  

end

app/models/about_us.rb
class AboutUs < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/contact_us.rb
class ContactUs < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_item
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :price, :quantity, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  mount_uploader :image, ImagesUploader

  validates :name, :price, :stock_quantity, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @updated = Product.where('updated = ?', true)
    @new = Product.where('new = ?', true)
    @comingsoon = Product.where('released = ?', false)
  end

  def aboutus
    @aboutus = AboutUs.first
  end
end

app/controllers/order_item_controller.rb
class OrderItemController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.order(:created_at).reverse
  end

  def boardgames
    @products = Product.where('category_id = 2')
  end

  def tradingcards
    @products = Product.where('category_id = 1')
  end

  def miniatures
    @products = Product.where('category_id = 4')
  end

  def roleplaying
    @products = Product.where('category_id = 5')
  end

  def accessories
    @products = Product.where('category_id = 3')
  end

  def show
  end

  def search_results
    wildcard_keywords = "%#{params[:search_keywords]}%"
    @search = Product.where('name LIKE ?', wildcard_keywords)
    @category_search = Product.where('name LIKE ? AND category_id = ?',
                                     wildcard_keywords,
                                     params[:category_id])
  end
end

app/controllers/province_controller.rb
class ProvinceController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/views/home/_header.html.erb
<nav>
	<ul>
		<li>Welcome</li>
		<li><a href="#" >Sign Up</a> | <a href="#">Log In</a></li>
		<li class="right">X Items In Cart $XXX.XX</li>	
	</ul>
</nav>

<p><%= image_tag("1500x200.png", class: "header_image") %></p>

<nav id="content_nav">
	<ul>
		<li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'Products', products_path %></li>
		<li><a href="#">Newsletter</a></li>
		<li><a href="#">Events</a></li>
		<li><a href="#">Game Demos</a></li>
		<li><%= link_to 'About Us', aboutus_path %></li>
		<li class="right">
            <%= form_tag search_results_path, method: :get do %>
              <%= text_field_tag :search_keywords %>
              
              <%= select_tag(:category_id, options_for_select([['', 0], ['CCG', 1], ['Boardgames', 2], ['Table Top Accessories', 3], ['Miniatures', 4], ['Role Playing', 5]])) %>
              <%= submit_tag 'Search' %>
            <% end %>
		</li>
	</ul>
</nav>

app/views/home/_home_content.html.erb
<%= render 'products/sidebar' %>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
    <div class="front">
		<h2>Featured Products</h2>
		<%= render partial: 'products/products', collection: @updated %>
	</div>
	<div class="front">
		<h2>New Products</h2>
		<%= render partial: 'products/products', collection: @new %>
	</div>
	<div class="front">
		<h2>Coming Soon</h2>
		<%= render partial: 'products/products', collection: @comingsoon %>
	</div>
</div>

app/views/home/aboutus.html.erb
<%= render 'header' %>

<%= render 'products/sidebar' %>

<div id="content">
  <% @aboutus = AboutUs.first %>
  <h2><%= @aboutus.title%></h2>
  <p><%= @aboutus.body %></p>
</div>

<br />
<br />
<br />

<div>
	<% @contactus = ContactUs.first %>
	<h2>Contact Us</h2>
	<p><%= @contactus.phone_number %></p>
	<p><%= @contactus.email %></p>
	<p><%= @contactus.address %></p>
	<p><%= @contactus.postal_code %></p>
</div>

app/views/home/index.html.erb
<%= render 'header' %>

<%= render 'home_content' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoardWalkers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_products.html.erb
<div id="products">
	<p><%= products.name %></p>
	<% if products.image != "" then %>
		<%= image_tag(products.image, class: "product_image") %>
	<% else %>
		<%= image_tag("No_picture_available.png", class: "product_image") %>
	<% end %>
	<p><%= products.description %></p>
	<p>Price: <%= number_to_currency(products.price) %></p>
	<% if products.stock_quantity >= 5 then %>
		<p id="instock">In Stock</p>
	<% elsif products.stock_quantity <=5 && products.stock_quantity >0 then %>
		<p id="lowstock">Low Stock</p>
	<% else %>
		<p id="outofstock">Out of Stock</p>
	<% end %>
</div>

app/views/products/_sidebar.html.erb
<nav id="side_bar">
	<li><a href="#">Coming Soon</a></li>
	<li><%= link_to 'Boardgames', boardgames_path %></li>
	<li><%= link_to 'Trading Cards', tradingcards_path %></li>
	<li><%= link_to 'Miniatures', miniatures_path %></li>
	<li><%= link_to 'Role Playing', roleplaying_path %></li>
	<li><%= link_to 'Accessories', accessories_path %></li>
</nav>

app/views/products/accessories.html.erb
<%= render 'home/header' %>

<%= render 'sidebar' %>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
	<%= render partial: 'products', collection: @products %>
</div>

app/views/products/boardgames.html.erb
<%= render 'home/header' %>

<%= render 'sidebar' %>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
	<%= render partial: 'products', collection: @products %>
</div>

app/views/products/index.html.erb
<%= render 'home/header' %>

<nav id="side_bar">
	<li><a href="#">Coming Soon</a></li>
	<li><a href="#">Boardgames</a></li>
	<li><a href="#">Trading Cards</a></li>
	<li><a href="#">Miniatures</a></li>
	<li><a href="#">Role Playing</a></li>
	<li><a href="#">Dice</a></li>
</nav>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
	<%= render partial: 'products', collection: @products %>
</div>

app/views/products/miniatures.html.erb
<%= render 'home/header' %>

<%= render 'sidebar' %>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
	<%= render partial: 'products', collection: @products %>
</div>

app/views/products/roleplaying.html.erb
<%= render 'home/header' %>

<%= render 'sidebar' %>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
	<%= render partial: 'products', collection: @products %>
</div>

app/views/products/search_results.html.erb
<%= render 'home/header' %>

<%= render 'sidebar' %>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
	<% if params[:category_id] == "0" %>
		<div class="search">
			<h2>Search Results for '<%= params[:search_keywords] %>'</h2>
			<% if @search.size.zero? %>
		      <p>No products found.</p>
			<% else %>
			    <p><%= pluralize(@search.size, 'Product') %> Found. </p>
			    <%= render partial: 'products', collection: @search %>
			<% end %>
		</div>
	<% else %>
		<div class="search">
		<h2>Search Results for '<%= params[:search_keywords] %>'</h2>
		<% if @category_search.size.zero? %>
	      <p>No products found.</p>
		<% else %>
		    <p><%= pluralize(@category_search.size, 'Product') %> Found in <%= Category.find(id = params[:category_id]).name %>. </p>
            <%= render partial: 'products', collection: @category_search %>
		<% end %>
	</div>
	<% end %>
</div>

app/views/products/tradingcards.html.erb
<%= render 'home/header' %>

<%= render 'sidebar' %>

<div id="content">
	<%= image_tag("1500x200.png", class: "content_image") %>
	<%= render partial: 'products', collection: @products %>
</div>